version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      - DB_TYPE=sqlite
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-admin123}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Asia/Seoul}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows:rw
      - ./custom-nodes:/home/node/.n8n/custom:rw
    networks:
      - n8n-network

  # PostgreSQL 데이터베이스 (옵션)
  # postgres:
  #   image: postgres:13
  #   container_name: n8n-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: n8n
  #     POSTGRES_USER: n8n
  #     POSTGRES_PASSWORD: n8n_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - n8n-network

volumes:
  n8n_data:
  # postgres_data:

networks:
  n8n-network:
    driver: bridge
